apiVersion: v1
kind: Secret
metadata:
  name: app-wordpress-secret
  namespace: wordpress
type: Opaque
data:
  wordpress_db_password: bWlrZQ==
  mysql_password: bWlrZQ==
  mysql_random_root_password: MQ==
